# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [102]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [103]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)
'''
with open ('anna.txt', 'r') as f:
    text = f.read()

vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)
'''

"\nwith open ('anna.txt', 'r') as f:\n    text = f.read()\n\nvocab = sorted(set(text))\nvocab_to_int = {c: i for i, c in enumerate(vocab)}\nint_to_vocab = dict(enumerate(vocab))\nencoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)\n"

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [104]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [105]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70])

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [106]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [107]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # n_seqs 만큼 batch에서 이동을 한다.
    # Get the number of characters per batch and number of batches we can make

    batch_size = n_seqs * n_steps
    print('batch_size: ', batch_size)
    print('len(arr): ', len(arr))
    n_batches = len(arr) // batch_size
    print('n_batchs: ', n_batches)
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * batch_size]
    
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    print('len(arr.reshape): ', len(arr))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [108]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

batch_size:  500
len(arr):  1985223
n_batchs:  3970
len(arr.reshape):  10


In [109]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]

y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [110]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [111]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [112]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat(lstm_output, axis=1)
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        # Create the weight and bias variables here
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predicts')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [113]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped =  tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [114]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [115]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN and collect the outputs
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [123]:
batch_size = 100         # Sequences per batch
num_steps = 100          # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [124]:
epochs = 20
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

batch_size:  10000
len(arr):  1985223
n_batchs:  198
len(arr.reshape):  100
Epoch: 1/20...  Training Step: 1...  Training loss: 4.4169...  2.4275 sec/batch
Epoch: 1/20...  Training Step: 2...  Training loss: 4.3133...  2.3693 sec/batch
Epoch: 1/20...  Training Step: 3...  Training loss: 3.7296...  2.4255 sec/batch
Epoch: 1/20...  Training Step: 4...  Training loss: 4.8900...  2.3432 sec/batch
Epoch: 1/20...  Training Step: 5...  Training loss: 4.2089...  2.3011 sec/batch
Epoch: 1/20...  Training Step: 6...  Training loss: 3.9403...  2.3292 sec/batch
Epoch: 1/20...  Training Step: 7...  Training loss: 3.7794...  2.3051 sec/batch
Epoch: 1/20...  Training Step: 8...  Training loss: 3.6426...  2.3272 sec/batch
Epoch: 1/20...  Training Step: 9...  Training loss: 3.4832...  2.3292 sec/batch
Epoch: 1/20...  Training Step: 10...  Training loss: 3.4666...  2.3352 sec/batch
Epoch: 1/20...  Training Step: 11...  Training loss: 3.4125...  2.2981 sec/batch
Epoch: 1/20...  Training Step: 12...  Trai

Epoch: 1/20...  Training Step: 102...  Training loss: 3.1074...  2.3533 sec/batch
Epoch: 1/20...  Training Step: 103...  Training loss: 3.1068...  2.3663 sec/batch
Epoch: 1/20...  Training Step: 104...  Training loss: 3.0982...  2.4134 sec/batch
Epoch: 1/20...  Training Step: 105...  Training loss: 3.0962...  2.4014 sec/batch
Epoch: 1/20...  Training Step: 106...  Training loss: 3.0906...  2.3392 sec/batch
Epoch: 1/20...  Training Step: 107...  Training loss: 3.0713...  2.3352 sec/batch
Epoch: 1/20...  Training Step: 108...  Training loss: 3.0800...  2.3553 sec/batch
Epoch: 1/20...  Training Step: 109...  Training loss: 3.0877...  2.3132 sec/batch
Epoch: 1/20...  Training Step: 110...  Training loss: 3.0390...  2.3051 sec/batch
Epoch: 1/20...  Training Step: 111...  Training loss: 3.0596...  2.3563 sec/batch
Epoch: 1/20...  Training Step: 112...  Training loss: 3.0619...  2.3362 sec/batch
Epoch: 1/20...  Training Step: 113...  Training loss: 3.0512...  2.3021 sec/batch
Epoch: 1/20...  

Epoch: 2/20...  Training Step: 201...  Training loss: 2.4675...  2.2941 sec/batch
Epoch: 2/20...  Training Step: 202...  Training loss: 2.4797...  2.3101 sec/batch
Epoch: 2/20...  Training Step: 203...  Training loss: 2.4792...  2.2951 sec/batch
Epoch: 2/20...  Training Step: 204...  Training loss: 2.4726...  2.2941 sec/batch
Epoch: 2/20...  Training Step: 205...  Training loss: 2.4807...  2.3031 sec/batch
Epoch: 2/20...  Training Step: 206...  Training loss: 2.4750...  2.3563 sec/batch
Epoch: 2/20...  Training Step: 207...  Training loss: 2.4938...  2.3613 sec/batch
Epoch: 2/20...  Training Step: 208...  Training loss: 2.4678...  2.3101 sec/batch
Epoch: 2/20...  Training Step: 209...  Training loss: 2.4501...  2.2921 sec/batch
Epoch: 2/20...  Training Step: 210...  Training loss: 2.4727...  2.3041 sec/batch
Epoch: 2/20...  Training Step: 211...  Training loss: 2.4671...  2.2961 sec/batch
Epoch: 2/20...  Training Step: 212...  Training loss: 2.4948...  2.3011 sec/batch
Epoch: 2/20...  

Epoch: 2/20...  Training Step: 301...  Training loss: 2.2310...  2.3503 sec/batch
Epoch: 2/20...  Training Step: 302...  Training loss: 2.2435...  2.3733 sec/batch
Epoch: 2/20...  Training Step: 303...  Training loss: 2.2254...  2.3111 sec/batch
Epoch: 2/20...  Training Step: 304...  Training loss: 2.2414...  2.2971 sec/batch
Epoch: 2/20...  Training Step: 305...  Training loss: 2.2331...  2.2961 sec/batch
Epoch: 2/20...  Training Step: 306...  Training loss: 2.2607...  2.2921 sec/batch
Epoch: 2/20...  Training Step: 307...  Training loss: 2.2525...  2.3081 sec/batch
Epoch: 2/20...  Training Step: 308...  Training loss: 2.2231...  2.3432 sec/batch
Epoch: 2/20...  Training Step: 309...  Training loss: 2.2423...  2.3543 sec/batch
Epoch: 2/20...  Training Step: 310...  Training loss: 2.2435...  2.3051 sec/batch
Epoch: 2/20...  Training Step: 311...  Training loss: 2.2285...  2.2881 sec/batch
Epoch: 2/20...  Training Step: 312...  Training loss: 2.2186...  2.2931 sec/batch
Epoch: 2/20...  

Epoch: 3/20...  Training Step: 400...  Training loss: 2.0808...  2.3001 sec/batch
Epoch: 3/20...  Training Step: 401...  Training loss: 2.0913...  2.2941 sec/batch
Epoch: 3/20...  Training Step: 402...  Training loss: 2.0637...  2.2771 sec/batch
Epoch: 3/20...  Training Step: 403...  Training loss: 2.0918...  2.3603 sec/batch
Epoch: 3/20...  Training Step: 404...  Training loss: 2.0867...  2.3432 sec/batch
Epoch: 3/20...  Training Step: 405...  Training loss: 2.1197...  2.3212 sec/batch
Epoch: 3/20...  Training Step: 406...  Training loss: 2.0788...  2.3041 sec/batch
Epoch: 3/20...  Training Step: 407...  Training loss: 2.0662...  2.3232 sec/batch
Epoch: 3/20...  Training Step: 408...  Training loss: 2.0593...  2.2971 sec/batch
Epoch: 3/20...  Training Step: 409...  Training loss: 2.0799...  2.2901 sec/batch
Epoch: 3/20...  Training Step: 410...  Training loss: 2.1070...  2.3633 sec/batch
Epoch: 3/20...  Training Step: 411...  Training loss: 2.0610...  2.3332 sec/batch
Epoch: 3/20...  

Epoch: 3/20...  Training Step: 500...  Training loss: 1.9529...  2.2861 sec/batch
Epoch: 3/20...  Training Step: 501...  Training loss: 1.9401...  2.3071 sec/batch
Epoch: 3/20...  Training Step: 502...  Training loss: 1.9510...  2.2871 sec/batch
Epoch: 3/20...  Training Step: 503...  Training loss: 1.9495...  2.2991 sec/batch
Epoch: 3/20...  Training Step: 504...  Training loss: 1.9706...  2.2881 sec/batch
Epoch: 3/20...  Training Step: 505...  Training loss: 1.9619...  2.3392 sec/batch
Epoch: 3/20...  Training Step: 506...  Training loss: 1.9672...  2.3583 sec/batch
Epoch: 3/20...  Training Step: 507...  Training loss: 1.9500...  2.3152 sec/batch
Epoch: 3/20...  Training Step: 508...  Training loss: 1.9442...  2.2961 sec/batch
Epoch: 3/20...  Training Step: 509...  Training loss: 1.9524...  2.3362 sec/batch
Epoch: 3/20...  Training Step: 510...  Training loss: 1.9345...  2.2991 sec/batch
Epoch: 3/20...  Training Step: 511...  Training loss: 1.9381...  2.3111 sec/batch
Epoch: 3/20...  

Epoch: 4/20...  Training Step: 599...  Training loss: 1.8731...  2.3472 sec/batch
Epoch: 4/20...  Training Step: 600...  Training loss: 1.8257...  2.3272 sec/batch
Epoch: 4/20...  Training Step: 601...  Training loss: 1.8711...  2.3041 sec/batch
Epoch: 4/20...  Training Step: 602...  Training loss: 1.8615...  2.2941 sec/batch
Epoch: 4/20...  Training Step: 603...  Training loss: 1.8994...  2.2821 sec/batch
Epoch: 4/20...  Training Step: 604...  Training loss: 1.8608...  2.2951 sec/batch
Epoch: 4/20...  Training Step: 605...  Training loss: 1.8438...  2.2951 sec/batch
Epoch: 4/20...  Training Step: 606...  Training loss: 1.8441...  2.2861 sec/batch
Epoch: 4/20...  Training Step: 607...  Training loss: 1.8631...  2.3342 sec/batch
Epoch: 4/20...  Training Step: 608...  Training loss: 1.8949...  2.3422 sec/batch
Epoch: 4/20...  Training Step: 609...  Training loss: 1.8504...  2.3061 sec/batch
Epoch: 4/20...  Training Step: 610...  Training loss: 1.8446...  2.3101 sec/batch
Epoch: 4/20...  

Epoch: 4/20...  Training Step: 699...  Training loss: 1.7785...  2.2961 sec/batch
Epoch: 4/20...  Training Step: 700...  Training loss: 1.7814...  2.3051 sec/batch
Epoch: 4/20...  Training Step: 701...  Training loss: 1.7865...  2.3472 sec/batch
Epoch: 4/20...  Training Step: 702...  Training loss: 1.7964...  2.3302 sec/batch
Epoch: 4/20...  Training Step: 703...  Training loss: 1.7918...  2.2981 sec/batch
Epoch: 4/20...  Training Step: 704...  Training loss: 1.7997...  2.2901 sec/batch
Epoch: 4/20...  Training Step: 705...  Training loss: 1.7874...  2.3142 sec/batch
Epoch: 4/20...  Training Step: 706...  Training loss: 1.7741...  2.2981 sec/batch
Epoch: 4/20...  Training Step: 707...  Training loss: 1.7888...  2.3041 sec/batch
Epoch: 4/20...  Training Step: 708...  Training loss: 1.7679...  2.3041 sec/batch
Epoch: 4/20...  Training Step: 709...  Training loss: 1.7615...  2.3192 sec/batch
Epoch: 4/20...  Training Step: 710...  Training loss: 1.7361...  2.3523 sec/batch
Epoch: 4/20...  

Epoch: 5/20...  Training Step: 798...  Training loss: 1.6822...  2.3041 sec/batch
Epoch: 5/20...  Training Step: 799...  Training loss: 1.7273...  2.2841 sec/batch
Epoch: 5/20...  Training Step: 800...  Training loss: 1.7113...  2.2961 sec/batch
Epoch: 5/20...  Training Step: 801...  Training loss: 1.7590...  2.2901 sec/batch
Epoch: 5/20...  Training Step: 802...  Training loss: 1.7209...  2.2991 sec/batch
Epoch: 5/20...  Training Step: 803...  Training loss: 1.6985...  2.3322 sec/batch
Epoch: 5/20...  Training Step: 804...  Training loss: 1.7086...  2.3392 sec/batch
Epoch: 5/20...  Training Step: 805...  Training loss: 1.7140...  2.3031 sec/batch
Epoch: 5/20...  Training Step: 806...  Training loss: 1.7649...  2.3041 sec/batch
Epoch: 5/20...  Training Step: 807...  Training loss: 1.7225...  2.2931 sec/batch
Epoch: 5/20...  Training Step: 808...  Training loss: 1.6994...  2.2951 sec/batch
Epoch: 5/20...  Training Step: 809...  Training loss: 1.7284...  2.2981 sec/batch
Epoch: 5/20...  

Epoch: 5/20...  Training Step: 898...  Training loss: 1.6518...  2.3362 sec/batch
Epoch: 5/20...  Training Step: 899...  Training loss: 1.6571...  2.3583 sec/batch
Epoch: 5/20...  Training Step: 900...  Training loss: 1.6639...  2.3071 sec/batch
Epoch: 5/20...  Training Step: 901...  Training loss: 1.6744...  2.2901 sec/batch
Epoch: 5/20...  Training Step: 902...  Training loss: 1.6807...  2.2981 sec/batch
Epoch: 5/20...  Training Step: 903...  Training loss: 1.6587...  2.3051 sec/batch
Epoch: 5/20...  Training Step: 904...  Training loss: 1.6549...  2.3122 sec/batch
Epoch: 5/20...  Training Step: 905...  Training loss: 1.6665...  2.3232 sec/batch
Epoch: 5/20...  Training Step: 906...  Training loss: 1.6576...  2.3663 sec/batch
Epoch: 5/20...  Training Step: 907...  Training loss: 1.6378...  2.2961 sec/batch
Epoch: 5/20...  Training Step: 908...  Training loss: 1.6251...  2.2911 sec/batch
Epoch: 5/20...  Training Step: 909...  Training loss: 1.6616...  2.3021 sec/batch
Epoch: 5/20...  

Epoch: 6/20...  Training Step: 997...  Training loss: 1.6304...  2.3011 sec/batch
Epoch: 6/20...  Training Step: 998...  Training loss: 1.6189...  2.3001 sec/batch
Epoch: 6/20...  Training Step: 999...  Training loss: 1.6438...  2.2941 sec/batch
Epoch: 6/20...  Training Step: 1000...  Training loss: 1.6032...  2.3482 sec/batch
Epoch: 6/20...  Training Step: 1001...  Training loss: 1.6004...  2.3392 sec/batch
Epoch: 6/20...  Training Step: 1002...  Training loss: 1.6066...  2.3031 sec/batch
Epoch: 6/20...  Training Step: 1003...  Training loss: 1.6146...  2.2971 sec/batch
Epoch: 6/20...  Training Step: 1004...  Training loss: 1.6662...  2.2931 sec/batch
Epoch: 6/20...  Training Step: 1005...  Training loss: 1.6041...  2.2931 sec/batch
Epoch: 6/20...  Training Step: 1006...  Training loss: 1.6085...  2.3041 sec/batch
Epoch: 6/20...  Training Step: 1007...  Training loss: 1.6234...  2.3422 sec/batch
Epoch: 6/20...  Training Step: 1008...  Training loss: 1.6549...  2.3362 sec/batch
Epoch: 

Epoch: 6/20...  Training Step: 1096...  Training loss: 1.5848...  2.3593 sec/batch
Epoch: 6/20...  Training Step: 1097...  Training loss: 1.5848...  2.2761 sec/batch
Epoch: 6/20...  Training Step: 1098...  Training loss: 1.5731...  2.3081 sec/batch
Epoch: 6/20...  Training Step: 1099...  Training loss: 1.5886...  2.3172 sec/batch
Epoch: 6/20...  Training Step: 1100...  Training loss: 1.5989...  2.2951 sec/batch
Epoch: 6/20...  Training Step: 1101...  Training loss: 1.5765...  2.3061 sec/batch
Epoch: 6/20...  Training Step: 1102...  Training loss: 1.5768...  2.3482 sec/batch
Epoch: 6/20...  Training Step: 1103...  Training loss: 1.5823...  2.3472 sec/batch
Epoch: 6/20...  Training Step: 1104...  Training loss: 1.5699...  2.2951 sec/batch
Epoch: 6/20...  Training Step: 1105...  Training loss: 1.5602...  2.3041 sec/batch
Epoch: 6/20...  Training Step: 1106...  Training loss: 1.5469...  2.3081 sec/batch
Epoch: 6/20...  Training Step: 1107...  Training loss: 1.5855...  2.3031 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1194...  Training loss: 1.5258...  2.3543 sec/batch
Epoch: 7/20...  Training Step: 1195...  Training loss: 1.5651...  2.3543 sec/batch
Epoch: 7/20...  Training Step: 1196...  Training loss: 1.5430...  2.3482 sec/batch
Epoch: 7/20...  Training Step: 1197...  Training loss: 1.5791...  2.3924 sec/batch
Epoch: 7/20...  Training Step: 1198...  Training loss: 1.5388...  2.4475 sec/batch
Epoch: 7/20...  Training Step: 1199...  Training loss: 1.5349...  2.4044 sec/batch
Epoch: 7/20...  Training Step: 1200...  Training loss: 1.5396...  2.4766 sec/batch
Epoch: 7/20...  Training Step: 1201...  Training loss: 1.5381...  2.5398 sec/batch
Epoch: 7/20...  Training Step: 1202...  Training loss: 1.5729...  2.4174 sec/batch
Epoch: 7/20...  Training Step: 1203...  Training loss: 1.5483...  2.3803 sec/batch
Epoch: 7/20...  Training Step: 1204...  Training loss: 1.5332...  2.4245 sec/batch
Epoch: 7/20...  Training Step: 1205...  Training loss: 1.5532...  2.5668 sec/batch
Epoc

Epoch: 7/20...  Training Step: 1293...  Training loss: 1.5055...  2.2901 sec/batch
Epoch: 7/20...  Training Step: 1294...  Training loss: 1.4988...  2.2921 sec/batch
Epoch: 7/20...  Training Step: 1295...  Training loss: 1.5151...  2.2901 sec/batch
Epoch: 7/20...  Training Step: 1296...  Training loss: 1.5040...  2.2891 sec/batch
Epoch: 7/20...  Training Step: 1297...  Training loss: 1.5102...  2.3111 sec/batch
Epoch: 7/20...  Training Step: 1298...  Training loss: 1.5339...  2.2961 sec/batch
Epoch: 7/20...  Training Step: 1299...  Training loss: 1.4955...  2.3232 sec/batch
Epoch: 7/20...  Training Step: 1300...  Training loss: 1.5075...  2.3593 sec/batch
Epoch: 7/20...  Training Step: 1301...  Training loss: 1.5156...  2.2901 sec/batch
Epoch: 7/20...  Training Step: 1302...  Training loss: 1.4939...  2.3101 sec/batch
Epoch: 7/20...  Training Step: 1303...  Training loss: 1.4857...  2.2961 sec/batch
Epoch: 7/20...  Training Step: 1304...  Training loss: 1.4748...  2.3001 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1391...  Training loss: 1.4763...  2.2811 sec/batch
Epoch: 8/20...  Training Step: 1392...  Training loss: 1.4486...  2.2891 sec/batch
Epoch: 8/20...  Training Step: 1393...  Training loss: 1.4955...  2.3051 sec/batch
Epoch: 8/20...  Training Step: 1394...  Training loss: 1.4764...  2.3061 sec/batch
Epoch: 8/20...  Training Step: 1395...  Training loss: 1.4997...  2.2931 sec/batch
Epoch: 8/20...  Training Step: 1396...  Training loss: 1.4759...  2.2891 sec/batch
Epoch: 8/20...  Training Step: 1397...  Training loss: 1.4643...  2.2911 sec/batch
Epoch: 8/20...  Training Step: 1398...  Training loss: 1.4705...  2.2931 sec/batch
Epoch: 8/20...  Training Step: 1399...  Training loss: 1.4821...  2.2921 sec/batch
Epoch: 8/20...  Training Step: 1400...  Training loss: 1.5076...  2.2981 sec/batch
Epoch: 8/20...  Training Step: 1401...  Training loss: 1.4740...  2.3533 sec/batch
Epoch: 8/20...  Training Step: 1402...  Training loss: 1.4564...  2.3332 sec/batch
Epoc

Epoch: 8/20...  Training Step: 1490...  Training loss: 1.4444...  2.3202 sec/batch
Epoch: 8/20...  Training Step: 1491...  Training loss: 1.4440...  2.2730 sec/batch
Epoch: 8/20...  Training Step: 1492...  Training loss: 1.4406...  2.3122 sec/batch
Epoch: 8/20...  Training Step: 1493...  Training loss: 1.4596...  2.3071 sec/batch
Epoch: 8/20...  Training Step: 1494...  Training loss: 1.4484...  2.2851 sec/batch
Epoch: 8/20...  Training Step: 1495...  Training loss: 1.4422...  2.3011 sec/batch
Epoch: 8/20...  Training Step: 1496...  Training loss: 1.4776...  2.2971 sec/batch
Epoch: 8/20...  Training Step: 1497...  Training loss: 1.4323...  2.4074 sec/batch
Epoch: 8/20...  Training Step: 1498...  Training loss: 1.4534...  2.3142 sec/batch
Epoch: 8/20...  Training Step: 1499...  Training loss: 1.4555...  2.2941 sec/batch
Epoch: 8/20...  Training Step: 1500...  Training loss: 1.4220...  2.3061 sec/batch
Epoch: 8/20...  Training Step: 1501...  Training loss: 1.4294...  2.3091 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1588...  Training loss: 1.4553...  2.3101 sec/batch
Epoch: 9/20...  Training Step: 1589...  Training loss: 1.4230...  2.3081 sec/batch
Epoch: 9/20...  Training Step: 1590...  Training loss: 1.4137...  2.3503 sec/batch
Epoch: 9/20...  Training Step: 1591...  Training loss: 1.4405...  2.3372 sec/batch
Epoch: 9/20...  Training Step: 1592...  Training loss: 1.4335...  2.2961 sec/batch
Epoch: 9/20...  Training Step: 1593...  Training loss: 1.4457...  2.2891 sec/batch
Epoch: 9/20...  Training Step: 1594...  Training loss: 1.4229...  2.3051 sec/batch
Epoch: 9/20...  Training Step: 1595...  Training loss: 1.4157...  2.2871 sec/batch
Epoch: 9/20...  Training Step: 1596...  Training loss: 1.4296...  2.3152 sec/batch
Epoch: 9/20...  Training Step: 1597...  Training loss: 1.4353...  2.3182 sec/batch
Epoch: 9/20...  Training Step: 1598...  Training loss: 1.4633...  2.3362 sec/batch
Epoch: 9/20...  Training Step: 1599...  Training loss: 1.4251...  2.3362 sec/batch
Epoc

Epoch: 9/20...  Training Step: 1687...  Training loss: 1.4205...  2.3081 sec/batch
Epoch: 9/20...  Training Step: 1688...  Training loss: 1.4043...  2.2861 sec/batch
Epoch: 9/20...  Training Step: 1689...  Training loss: 1.4112...  2.2981 sec/batch
Epoch: 9/20...  Training Step: 1690...  Training loss: 1.3996...  2.2961 sec/batch
Epoch: 9/20...  Training Step: 1691...  Training loss: 1.4121...  2.3081 sec/batch
Epoch: 9/20...  Training Step: 1692...  Training loss: 1.4086...  2.3332 sec/batch
Epoch: 9/20...  Training Step: 1693...  Training loss: 1.4009...  2.3262 sec/batch
Epoch: 9/20...  Training Step: 1694...  Training loss: 1.4335...  2.3031 sec/batch
Epoch: 9/20...  Training Step: 1695...  Training loss: 1.3979...  2.2831 sec/batch
Epoch: 9/20...  Training Step: 1696...  Training loss: 1.4119...  2.3132 sec/batch
Epoch: 9/20...  Training Step: 1697...  Training loss: 1.4141...  2.2951 sec/batch
Epoch: 9/20...  Training Step: 1698...  Training loss: 1.3999...  2.3122 sec/batch
Epoc

Epoch: 10/20...  Training Step: 1785...  Training loss: 1.4104...  2.3001 sec/batch
Epoch: 10/20...  Training Step: 1786...  Training loss: 1.4171...  2.2971 sec/batch
Epoch: 10/20...  Training Step: 1787...  Training loss: 1.3849...  2.3503 sec/batch
Epoch: 10/20...  Training Step: 1788...  Training loss: 1.3721...  2.3362 sec/batch
Epoch: 10/20...  Training Step: 1789...  Training loss: 1.4040...  2.2961 sec/batch
Epoch: 10/20...  Training Step: 1790...  Training loss: 1.3922...  2.2891 sec/batch
Epoch: 10/20...  Training Step: 1791...  Training loss: 1.4124...  2.2921 sec/batch
Epoch: 10/20...  Training Step: 1792...  Training loss: 1.3967...  2.3021 sec/batch
Epoch: 10/20...  Training Step: 1793...  Training loss: 1.3759...  2.2881 sec/batch
Epoch: 10/20...  Training Step: 1794...  Training loss: 1.3990...  2.3111 sec/batch
Epoch: 10/20...  Training Step: 1795...  Training loss: 1.4039...  2.3452 sec/batch
Epoch: 10/20...  Training Step: 1796...  Training loss: 1.4238...  2.3001 se

Epoch: 10/20...  Training Step: 1883...  Training loss: 1.3870...  2.3553 sec/batch
Epoch: 10/20...  Training Step: 1884...  Training loss: 1.3677...  2.2981 sec/batch
Epoch: 10/20...  Training Step: 1885...  Training loss: 1.3705...  2.3001 sec/batch
Epoch: 10/20...  Training Step: 1886...  Training loss: 1.3728...  2.2961 sec/batch
Epoch: 10/20...  Training Step: 1887...  Training loss: 1.3687...  2.2921 sec/batch
Epoch: 10/20...  Training Step: 1888...  Training loss: 1.3757...  2.2911 sec/batch
Epoch: 10/20...  Training Step: 1889...  Training loss: 1.3933...  2.3563 sec/batch
Epoch: 10/20...  Training Step: 1890...  Training loss: 1.3720...  2.3312 sec/batch
Epoch: 10/20...  Training Step: 1891...  Training loss: 1.3665...  2.3061 sec/batch
Epoch: 10/20...  Training Step: 1892...  Training loss: 1.4168...  2.2931 sec/batch
Epoch: 10/20...  Training Step: 1893...  Training loss: 1.3642...  2.3101 sec/batch
Epoch: 10/20...  Training Step: 1894...  Training loss: 1.3747...  2.3122 se

Epoch: 11/20...  Training Step: 1981...  Training loss: 1.5479...  2.3001 sec/batch
Epoch: 11/20...  Training Step: 1982...  Training loss: 1.3905...  2.2961 sec/batch
Epoch: 11/20...  Training Step: 1983...  Training loss: 1.3753...  2.2891 sec/batch
Epoch: 11/20...  Training Step: 1984...  Training loss: 1.3893...  2.3392 sec/batch
Epoch: 11/20...  Training Step: 1985...  Training loss: 1.3566...  2.3452 sec/batch
Epoch: 11/20...  Training Step: 1986...  Training loss: 1.3327...  2.2871 sec/batch
Epoch: 11/20...  Training Step: 1987...  Training loss: 1.3822...  2.3162 sec/batch
Epoch: 11/20...  Training Step: 1988...  Training loss: 1.3661...  2.2981 sec/batch
Epoch: 11/20...  Training Step: 1989...  Training loss: 1.3815...  2.2861 sec/batch
Epoch: 11/20...  Training Step: 1990...  Training loss: 1.3651...  2.3122 sec/batch
Epoch: 11/20...  Training Step: 1991...  Training loss: 1.3461...  2.3452 sec/batch
Epoch: 11/20...  Training Step: 1992...  Training loss: 1.3694...  2.3402 se

Epoch: 11/20...  Training Step: 2079...  Training loss: 1.3428...  2.3392 sec/batch
Epoch: 11/20...  Training Step: 2080...  Training loss: 1.3202...  2.3302 sec/batch
Epoch: 11/20...  Training Step: 2081...  Training loss: 1.3645...  2.2891 sec/batch
Epoch: 11/20...  Training Step: 2082...  Training loss: 1.3567...  2.2861 sec/batch
Epoch: 11/20...  Training Step: 2083...  Training loss: 1.3580...  2.2851 sec/batch
Epoch: 11/20...  Training Step: 2084...  Training loss: 1.3424...  2.2921 sec/batch
Epoch: 11/20...  Training Step: 2085...  Training loss: 1.3491...  2.2891 sec/batch
Epoch: 11/20...  Training Step: 2086...  Training loss: 1.3445...  2.3553 sec/batch
Epoch: 11/20...  Training Step: 2087...  Training loss: 1.3546...  2.3222 sec/batch
Epoch: 11/20...  Training Step: 2088...  Training loss: 1.3549...  2.2981 sec/batch
Epoch: 11/20...  Training Step: 2089...  Training loss: 1.3439...  2.3091 sec/batch
Epoch: 11/20...  Training Step: 2090...  Training loss: 1.3748...  2.3021 se

Epoch: 11/20...  Training Step: 2177...  Training loss: 1.3339...  2.2881 sec/batch
Epoch: 11/20...  Training Step: 2178...  Training loss: 1.3294...  2.3021 sec/batch
batch_size:  10000
len(arr):  1985223
n_batchs:  198
len(arr.reshape):  100
Epoch: 12/20...  Training Step: 2179...  Training loss: 1.5260...  2.2971 sec/batch
Epoch: 12/20...  Training Step: 2180...  Training loss: 1.3834...  2.2841 sec/batch
Epoch: 12/20...  Training Step: 2181...  Training loss: 1.3802...  2.3162 sec/batch
Epoch: 12/20...  Training Step: 2182...  Training loss: 1.3737...  2.3492 sec/batch
Epoch: 12/20...  Training Step: 2183...  Training loss: 1.3346...  2.3081 sec/batch
Epoch: 12/20...  Training Step: 2184...  Training loss: 1.3178...  2.2991 sec/batch
Epoch: 12/20...  Training Step: 2185...  Training loss: 1.3631...  2.2971 sec/batch
Epoch: 12/20...  Training Step: 2186...  Training loss: 1.3518...  2.2941 sec/batch
Epoch: 12/20...  Training Step: 2187...  Training loss: 1.3734...  2.3031 sec/batch


Epoch: 12/20...  Training Step: 2274...  Training loss: 1.3461...  2.3071 sec/batch
Epoch: 12/20...  Training Step: 2275...  Training loss: 1.3292...  2.3292 sec/batch
Epoch: 12/20...  Training Step: 2276...  Training loss: 1.2981...  2.3573 sec/batch
Epoch: 12/20...  Training Step: 2277...  Training loss: 1.3015...  2.2861 sec/batch
Epoch: 12/20...  Training Step: 2278...  Training loss: 1.2947...  2.2861 sec/batch
Epoch: 12/20...  Training Step: 2279...  Training loss: 1.3310...  2.2971 sec/batch
Epoch: 12/20...  Training Step: 2280...  Training loss: 1.3193...  2.3302 sec/batch
Epoch: 12/20...  Training Step: 2281...  Training loss: 1.3306...  2.3242 sec/batch
Epoch: 12/20...  Training Step: 2282...  Training loss: 1.3197...  2.2881 sec/batch
Epoch: 12/20...  Training Step: 2283...  Training loss: 1.3186...  2.3342 sec/batch
Epoch: 12/20...  Training Step: 2284...  Training loss: 1.3141...  2.3543 sec/batch
Epoch: 12/20...  Training Step: 2285...  Training loss: 1.3404...  2.2981 se

Epoch: 12/20...  Training Step: 2372...  Training loss: 1.3007...  2.3061 sec/batch
Epoch: 12/20...  Training Step: 2373...  Training loss: 1.2848...  2.3132 sec/batch
Epoch: 12/20...  Training Step: 2374...  Training loss: 1.3333...  2.3132 sec/batch
Epoch: 12/20...  Training Step: 2375...  Training loss: 1.3106...  2.2951 sec/batch
Epoch: 12/20...  Training Step: 2376...  Training loss: 1.3141...  2.3091 sec/batch
batch_size:  10000
len(arr):  1985223
n_batchs:  198
len(arr.reshape):  100
Epoch: 13/20...  Training Step: 2377...  Training loss: 1.4561...  2.3332 sec/batch
Epoch: 13/20...  Training Step: 2378...  Training loss: 1.3389...  2.3412 sec/batch
Epoch: 13/20...  Training Step: 2379...  Training loss: 1.3206...  2.3071 sec/batch
Epoch: 13/20...  Training Step: 2380...  Training loss: 1.3361...  2.2991 sec/batch
Epoch: 13/20...  Training Step: 2381...  Training loss: 1.3031...  2.2911 sec/batch
Epoch: 13/20...  Training Step: 2382...  Training loss: 1.2816...  2.2871 sec/batch


Epoch: 13/20...  Training Step: 2469...  Training loss: 1.2901...  2.3031 sec/batch
Epoch: 13/20...  Training Step: 2470...  Training loss: 1.2893...  2.2911 sec/batch
Epoch: 13/20...  Training Step: 2471...  Training loss: 1.3001...  2.3041 sec/batch
Epoch: 13/20...  Training Step: 2472...  Training loss: 1.3257...  2.3412 sec/batch
Epoch: 13/20...  Training Step: 2473...  Training loss: 1.3155...  2.3603 sec/batch
Epoch: 13/20...  Training Step: 2474...  Training loss: 1.2767...  2.2891 sec/batch
Epoch: 13/20...  Training Step: 2475...  Training loss: 1.2969...  2.3011 sec/batch
Epoch: 13/20...  Training Step: 2476...  Training loss: 1.2800...  2.2941 sec/batch
Epoch: 13/20...  Training Step: 2477...  Training loss: 1.3129...  2.3312 sec/batch
Epoch: 13/20...  Training Step: 2478...  Training loss: 1.3000...  2.2931 sec/batch
Epoch: 13/20...  Training Step: 2479...  Training loss: 1.3082...  2.3192 sec/batch
Epoch: 13/20...  Training Step: 2480...  Training loss: 1.3114...  2.3432 se

Epoch: 13/20...  Training Step: 2567...  Training loss: 1.2816...  2.3252 sec/batch
Epoch: 13/20...  Training Step: 2568...  Training loss: 1.2848...  2.3543 sec/batch
Epoch: 13/20...  Training Step: 2569...  Training loss: 1.3067...  2.3152 sec/batch
Epoch: 13/20...  Training Step: 2570...  Training loss: 1.2857...  2.2951 sec/batch
Epoch: 13/20...  Training Step: 2571...  Training loss: 1.2666...  2.2841 sec/batch
Epoch: 13/20...  Training Step: 2572...  Training loss: 1.3152...  2.3001 sec/batch
Epoch: 13/20...  Training Step: 2573...  Training loss: 1.2926...  2.2961 sec/batch
Epoch: 13/20...  Training Step: 2574...  Training loss: 1.2903...  2.3232 sec/batch
batch_size:  10000
len(arr):  1985223
n_batchs:  198
len(arr.reshape):  100
Epoch: 14/20...  Training Step: 2575...  Training loss: 1.4356...  2.3282 sec/batch
Epoch: 14/20...  Training Step: 2576...  Training loss: 1.3212...  2.3011 sec/batch
Epoch: 14/20...  Training Step: 2577...  Training loss: 1.3082...  2.2921 sec/batch


Epoch: 14/20...  Training Step: 2664...  Training loss: 1.2966...  2.2921 sec/batch
Epoch: 14/20...  Training Step: 2665...  Training loss: 1.2765...  2.2740 sec/batch
Epoch: 14/20...  Training Step: 2666...  Training loss: 1.2924...  2.2981 sec/batch
Epoch: 14/20...  Training Step: 2667...  Training loss: 1.2743...  2.2881 sec/batch
Epoch: 14/20...  Training Step: 2668...  Training loss: 1.2678...  2.2971 sec/batch
Epoch: 14/20...  Training Step: 2669...  Training loss: 1.2849...  2.3432 sec/batch
Epoch: 14/20...  Training Step: 2670...  Training loss: 1.2978...  2.3442 sec/batch
Epoch: 14/20...  Training Step: 2671...  Training loss: 1.2972...  2.2921 sec/batch
Epoch: 14/20...  Training Step: 2672...  Training loss: 1.2543...  2.3041 sec/batch
Epoch: 14/20...  Training Step: 2673...  Training loss: 1.2767...  2.2891 sec/batch
Epoch: 14/20...  Training Step: 2674...  Training loss: 1.2712...  2.3001 sec/batch
Epoch: 14/20...  Training Step: 2675...  Training loss: 1.3023...  2.3111 se

Epoch: 14/20...  Training Step: 2762...  Training loss: 1.2867...  2.3001 sec/batch
Epoch: 14/20...  Training Step: 2763...  Training loss: 1.2844...  2.2931 sec/batch
Epoch: 14/20...  Training Step: 2764...  Training loss: 1.2854...  2.3422 sec/batch
Epoch: 14/20...  Training Step: 2765...  Training loss: 1.2713...  2.3523 sec/batch
Epoch: 14/20...  Training Step: 2766...  Training loss: 1.2758...  2.2841 sec/batch
Epoch: 14/20...  Training Step: 2767...  Training loss: 1.2904...  2.2941 sec/batch
Epoch: 14/20...  Training Step: 2768...  Training loss: 1.2764...  2.2821 sec/batch
Epoch: 14/20...  Training Step: 2769...  Training loss: 1.2434...  2.2971 sec/batch
Epoch: 14/20...  Training Step: 2770...  Training loss: 1.3009...  2.2901 sec/batch
Epoch: 14/20...  Training Step: 2771...  Training loss: 1.2824...  2.3422 sec/batch
Epoch: 14/20...  Training Step: 2772...  Training loss: 1.2809...  2.3492 sec/batch
batch_size:  10000
len(arr):  1985223
n_batchs:  198
len(arr.reshape):  100


Epoch: 15/20...  Training Step: 2859...  Training loss: 1.2576...  2.3362 sec/batch
Epoch: 15/20...  Training Step: 2860...  Training loss: 1.2623...  2.3332 sec/batch
Epoch: 15/20...  Training Step: 2861...  Training loss: 1.2390...  2.2971 sec/batch
Epoch: 15/20...  Training Step: 2862...  Training loss: 1.2826...  2.2871 sec/batch
Epoch: 15/20...  Training Step: 2863...  Training loss: 1.2471...  2.3001 sec/batch
Epoch: 15/20...  Training Step: 2864...  Training loss: 1.2775...  2.3011 sec/batch
Epoch: 15/20...  Training Step: 2865...  Training loss: 1.2525...  2.2981 sec/batch
Epoch: 15/20...  Training Step: 2866...  Training loss: 1.2516...  2.3503 sec/batch
Epoch: 15/20...  Training Step: 2867...  Training loss: 1.2732...  2.3412 sec/batch
Epoch: 15/20...  Training Step: 2868...  Training loss: 1.2941...  2.3061 sec/batch
Epoch: 15/20...  Training Step: 2869...  Training loss: 1.2846...  2.3021 sec/batch
Epoch: 15/20...  Training Step: 2870...  Training loss: 1.2370...  2.3071 se

Epoch: 15/20...  Training Step: 2957...  Training loss: 1.2705...  2.3111 sec/batch
Epoch: 15/20...  Training Step: 2958...  Training loss: 1.2611...  2.2901 sec/batch
Epoch: 15/20...  Training Step: 2959...  Training loss: 1.3026...  2.2951 sec/batch
Epoch: 15/20...  Training Step: 2960...  Training loss: 1.2705...  2.3162 sec/batch
Epoch: 15/20...  Training Step: 2961...  Training loss: 1.2727...  2.3162 sec/batch
Epoch: 15/20...  Training Step: 2962...  Training loss: 1.2714...  2.3372 sec/batch
Epoch: 15/20...  Training Step: 2963...  Training loss: 1.2477...  2.2931 sec/batch
Epoch: 15/20...  Training Step: 2964...  Training loss: 1.2551...  2.2911 sec/batch
Epoch: 15/20...  Training Step: 2965...  Training loss: 1.2701...  2.2961 sec/batch
Epoch: 15/20...  Training Step: 2966...  Training loss: 1.2562...  2.3081 sec/batch
Epoch: 15/20...  Training Step: 2967...  Training loss: 1.2393...  2.3142 sec/batch
Epoch: 15/20...  Training Step: 2968...  Training loss: 1.2870...  2.3292 se

Epoch: 16/20...  Training Step: 3054...  Training loss: 1.2637...  2.2961 sec/batch
Epoch: 16/20...  Training Step: 3055...  Training loss: 1.2399...  2.3472 sec/batch
Epoch: 16/20...  Training Step: 3056...  Training loss: 1.2605...  2.3492 sec/batch
Epoch: 16/20...  Training Step: 3057...  Training loss: 1.2479...  2.2941 sec/batch
Epoch: 16/20...  Training Step: 3058...  Training loss: 1.2450...  2.2931 sec/batch
Epoch: 16/20...  Training Step: 3059...  Training loss: 1.2309...  2.3011 sec/batch
Epoch: 16/20...  Training Step: 3060...  Training loss: 1.2776...  2.2971 sec/batch
Epoch: 16/20...  Training Step: 3061...  Training loss: 1.2406...  2.3061 sec/batch
Epoch: 16/20...  Training Step: 3062...  Training loss: 1.2622...  2.3011 sec/batch
Epoch: 16/20...  Training Step: 3063...  Training loss: 1.2432...  2.3482 sec/batch
Epoch: 16/20...  Training Step: 3064...  Training loss: 1.2404...  2.4355 sec/batch
Epoch: 16/20...  Training Step: 3065...  Training loss: 1.2530...  2.3322 se

Epoch: 16/20...  Training Step: 3152...  Training loss: 1.2574...  2.2961 sec/batch
Epoch: 16/20...  Training Step: 3153...  Training loss: 1.2573...  2.2901 sec/batch
Epoch: 16/20...  Training Step: 3154...  Training loss: 1.2462...  2.3162 sec/batch
Epoch: 16/20...  Training Step: 3155...  Training loss: 1.2485...  2.3061 sec/batch
Epoch: 16/20...  Training Step: 3156...  Training loss: 1.2455...  2.2881 sec/batch
Epoch: 16/20...  Training Step: 3157...  Training loss: 1.2835...  2.3422 sec/batch
Epoch: 16/20...  Training Step: 3158...  Training loss: 1.2602...  2.3482 sec/batch
Epoch: 16/20...  Training Step: 3159...  Training loss: 1.2531...  2.2881 sec/batch
Epoch: 16/20...  Training Step: 3160...  Training loss: 1.2511...  2.2931 sec/batch
Epoch: 16/20...  Training Step: 3161...  Training loss: 1.2378...  2.3111 sec/batch
Epoch: 16/20...  Training Step: 3162...  Training loss: 1.2507...  2.3011 sec/batch
Epoch: 16/20...  Training Step: 3163...  Training loss: 1.2665...  2.2991 se

Epoch: 17/20...  Training Step: 3249...  Training loss: 1.2191...  2.2911 sec/batch
Epoch: 17/20...  Training Step: 3250...  Training loss: 1.2566...  2.2901 sec/batch
Epoch: 17/20...  Training Step: 3251...  Training loss: 1.2365...  2.3081 sec/batch
Epoch: 17/20...  Training Step: 3252...  Training loss: 1.2553...  2.3402 sec/batch
Epoch: 17/20...  Training Step: 3253...  Training loss: 1.2273...  2.3472 sec/batch
Epoch: 17/20...  Training Step: 3254...  Training loss: 1.2529...  2.3272 sec/batch
Epoch: 17/20...  Training Step: 3255...  Training loss: 1.2346...  2.3111 sec/batch
Epoch: 17/20...  Training Step: 3256...  Training loss: 1.2333...  2.2961 sec/batch
Epoch: 17/20...  Training Step: 3257...  Training loss: 1.2260...  2.2921 sec/batch
Epoch: 17/20...  Training Step: 3258...  Training loss: 1.2603...  2.2971 sec/batch
Epoch: 17/20...  Training Step: 3259...  Training loss: 1.2288...  2.3061 sec/batch
Epoch: 17/20...  Training Step: 3260...  Training loss: 1.2416...  2.3362 se

Epoch: 17/20...  Training Step: 3347...  Training loss: 1.2321...  2.3513 sec/batch
Epoch: 17/20...  Training Step: 3348...  Training loss: 1.2304...  2.3252 sec/batch
Epoch: 17/20...  Training Step: 3349...  Training loss: 1.2400...  2.3041 sec/batch
Epoch: 17/20...  Training Step: 3350...  Training loss: 1.2493...  2.3101 sec/batch
Epoch: 17/20...  Training Step: 3351...  Training loss: 1.2431...  2.3132 sec/batch
Epoch: 17/20...  Training Step: 3352...  Training loss: 1.2404...  2.2811 sec/batch
Epoch: 17/20...  Training Step: 3353...  Training loss: 1.2499...  2.3031 sec/batch
Epoch: 17/20...  Training Step: 3354...  Training loss: 1.2262...  2.3332 sec/batch
Epoch: 17/20...  Training Step: 3355...  Training loss: 1.2728...  2.3432 sec/batch
Epoch: 17/20...  Training Step: 3356...  Training loss: 1.2480...  2.3051 sec/batch
Epoch: 17/20...  Training Step: 3357...  Training loss: 1.2447...  2.2981 sec/batch
Epoch: 17/20...  Training Step: 3358...  Training loss: 1.2449...  2.3232 se

Epoch: 18/20...  Training Step: 3444...  Training loss: 1.2342...  2.2951 sec/batch
Epoch: 18/20...  Training Step: 3445...  Training loss: 1.2152...  2.3021 sec/batch
Epoch: 18/20...  Training Step: 3446...  Training loss: 1.2621...  2.2911 sec/batch
Epoch: 18/20...  Training Step: 3447...  Training loss: 1.2175...  2.3031 sec/batch
Epoch: 18/20...  Training Step: 3448...  Training loss: 1.2530...  2.2911 sec/batch
Epoch: 18/20...  Training Step: 3449...  Training loss: 1.2214...  2.3492 sec/batch
Epoch: 18/20...  Training Step: 3450...  Training loss: 1.2470...  2.3563 sec/batch
Epoch: 18/20...  Training Step: 3451...  Training loss: 1.2249...  2.2941 sec/batch
Epoch: 18/20...  Training Step: 3452...  Training loss: 1.2490...  2.2871 sec/batch
Epoch: 18/20...  Training Step: 3453...  Training loss: 1.2277...  2.2921 sec/batch
Epoch: 18/20...  Training Step: 3454...  Training loss: 1.2391...  2.3202 sec/batch
Epoch: 18/20...  Training Step: 3455...  Training loss: 1.2110...  2.2921 se

Epoch: 18/20...  Training Step: 3542...  Training loss: 1.2185...  2.2941 sec/batch
Epoch: 18/20...  Training Step: 3543...  Training loss: 1.2375...  2.2971 sec/batch
Epoch: 18/20...  Training Step: 3544...  Training loss: 1.2766...  2.3583 sec/batch
Epoch: 18/20...  Training Step: 3545...  Training loss: 1.2263...  2.3482 sec/batch
Epoch: 18/20...  Training Step: 3546...  Training loss: 1.2123...  2.3031 sec/batch
Epoch: 18/20...  Training Step: 3547...  Training loss: 1.2232...  2.3021 sec/batch
Epoch: 18/20...  Training Step: 3548...  Training loss: 1.2411...  2.3091 sec/batch
Epoch: 18/20...  Training Step: 3549...  Training loss: 1.2343...  2.2931 sec/batch
Epoch: 18/20...  Training Step: 3550...  Training loss: 1.2285...  2.2921 sec/batch
Epoch: 18/20...  Training Step: 3551...  Training loss: 1.2270...  2.3242 sec/batch
Epoch: 18/20...  Training Step: 3552...  Training loss: 1.2234...  2.3442 sec/batch
Epoch: 18/20...  Training Step: 3553...  Training loss: 1.2687...  2.2831 se

Epoch: 19/20...  Training Step: 3639...  Training loss: 1.2351...  2.3442 sec/batch
Epoch: 19/20...  Training Step: 3640...  Training loss: 1.2451...  2.3392 sec/batch
Epoch: 19/20...  Training Step: 3641...  Training loss: 1.2306...  2.2841 sec/batch
Epoch: 19/20...  Training Step: 3642...  Training loss: 1.2151...  2.2791 sec/batch
Epoch: 19/20...  Training Step: 3643...  Training loss: 1.2039...  2.2951 sec/batch
Epoch: 19/20...  Training Step: 3644...  Training loss: 1.2315...  2.2891 sec/batch
Epoch: 19/20...  Training Step: 3645...  Training loss: 1.2029...  2.2981 sec/batch
Epoch: 19/20...  Training Step: 3646...  Training loss: 1.2316...  2.3392 sec/batch
Epoch: 19/20...  Training Step: 3647...  Training loss: 1.2037...  2.3613 sec/batch
Epoch: 19/20...  Training Step: 3648...  Training loss: 1.2248...  2.2841 sec/batch
Epoch: 19/20...  Training Step: 3649...  Training loss: 1.2078...  2.2931 sec/batch
Epoch: 19/20...  Training Step: 3650...  Training loss: 1.2293...  2.3061 se

Epoch: 19/20...  Training Step: 3737...  Training loss: 1.2603...  2.2961 sec/batch
Epoch: 19/20...  Training Step: 3738...  Training loss: 1.2311...  2.3111 sec/batch
Epoch: 19/20...  Training Step: 3739...  Training loss: 1.2319...  2.2781 sec/batch
Epoch: 19/20...  Training Step: 3740...  Training loss: 1.2040...  2.2841 sec/batch
Epoch: 19/20...  Training Step: 3741...  Training loss: 1.2284...  2.3392 sec/batch
Epoch: 19/20...  Training Step: 3742...  Training loss: 1.2735...  2.3422 sec/batch
Epoch: 19/20...  Training Step: 3743...  Training loss: 1.2066...  2.2901 sec/batch
Epoch: 19/20...  Training Step: 3744...  Training loss: 1.2167...  2.2871 sec/batch
Epoch: 19/20...  Training Step: 3745...  Training loss: 1.2085...  2.3021 sec/batch
Epoch: 19/20...  Training Step: 3746...  Training loss: 1.2249...  2.2871 sec/batch
Epoch: 19/20...  Training Step: 3747...  Training loss: 1.2318...  2.2831 sec/batch
Epoch: 19/20...  Training Step: 3748...  Training loss: 1.2116...  2.3302 se

Epoch: 20/20...  Training Step: 3834...  Training loss: 1.2458...  2.2981 sec/batch
Epoch: 20/20...  Training Step: 3835...  Training loss: 1.2561...  2.2971 sec/batch
Epoch: 20/20...  Training Step: 3836...  Training loss: 1.2116...  2.3523 sec/batch
Epoch: 20/20...  Training Step: 3837...  Training loss: 1.2283...  2.3232 sec/batch
Epoch: 20/20...  Training Step: 3838...  Training loss: 1.2397...  2.2951 sec/batch
Epoch: 20/20...  Training Step: 3839...  Training loss: 1.2215...  2.2921 sec/batch
Epoch: 20/20...  Training Step: 3840...  Training loss: 1.2086...  2.2961 sec/batch
Epoch: 20/20...  Training Step: 3841...  Training loss: 1.1889...  2.2991 sec/batch
Epoch: 20/20...  Training Step: 3842...  Training loss: 1.2414...  2.3613 sec/batch
Epoch: 20/20...  Training Step: 3843...  Training loss: 1.1907...  2.3412 sec/batch
Epoch: 20/20...  Training Step: 3844...  Training loss: 1.2161...  2.3513 sec/batch
Epoch: 20/20...  Training Step: 3845...  Training loss: 1.2017...  2.2831 se

Epoch: 20/20...  Training Step: 3932...  Training loss: 1.2202...  2.3302 sec/batch
Epoch: 20/20...  Training Step: 3933...  Training loss: 1.2163...  2.3041 sec/batch
Epoch: 20/20...  Training Step: 3934...  Training loss: 1.2098...  2.2971 sec/batch
Epoch: 20/20...  Training Step: 3935...  Training loss: 1.2518...  2.2911 sec/batch
Epoch: 20/20...  Training Step: 3936...  Training loss: 1.2158...  2.2931 sec/batch
Epoch: 20/20...  Training Step: 3937...  Training loss: 1.2247...  2.2851 sec/batch
Epoch: 20/20...  Training Step: 3938...  Training loss: 1.1944...  2.3392 sec/batch
Epoch: 20/20...  Training Step: 3939...  Training loss: 1.2233...  2.3392 sec/batch
Epoch: 20/20...  Training Step: 3940...  Training loss: 1.2581...  2.3001 sec/batch
Epoch: 20/20...  Training Step: 3941...  Training loss: 1.2066...  2.2981 sec/batch
Epoch: 20/20...  Training Step: 3942...  Training loss: 1.1988...  2.2991 sec/batch
Epoch: 20/20...  Training Step: 3943...  Training loss: 1.2085...  2.2941 se

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [125]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints\\i3960_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3200_l512.ckpt"
all_mo

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [126]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [127]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [128]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints\\i3960_l512.ckpt'

In [129]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints\i3960_l512.ckpt
Farrand with sereness of the same the
sight of the porter, so so that he had no circle to hild. The party.
The consideration of the prayer of her force himself, and would have so taken
ut the sight of the prince's position, an intellectual form were not
lively, wore in sheeps, a consideration with him, what was hated in her
sister without him. That this, and the corner of the conversation that it
was the season of the service in which the chief cold bother, and she was
that the same interests with a convinced of her position in the significance
of the marsh had been a grut head of such answering, and to be the more only
there would not be so time and set in a bear in the conders, but he had to
send the porter, but there are anyone whee she seemed, the sort of tract
in the priest and the same stands, and the man's sort of service, because
it was shame to see anything, and that she could not come to him over his mother

In [130]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt
Fard." "
"We lad onder atos whe se hers on he har seod shethe ho wher tore tingend wong tis ore and and are ales tor the the wan one shad tas the sate hit he shas hite wint, he wot an ases ore to sist at het orer sisserare wo wh he ane arisighe and thir ones af at and on at ou hed she sones sesing ho to hhis ar the sot hhad wase thar ass here sithend wat he ter and onte hasd, wan athen ar tal ath on and torere son thes tand,
tadd him he whir ous and to he he alde the sor tin the ass at tass tom
southind, wis toten the herad tho sistin hit he sees and sase the he hes an ans ood the sereditig this har there anthe hans, sothe whis and to wat the wit has the sot ou the sissing thes handend weresen tas sete sh mos onther ante she an sos atito hha wherse sesse sad wiss hot at hes oo sess and tit sissoresin this alled on the wint oo harit hit alin tand, and hes atise sithe wor hes tomint, wos sot he were sone wan sate worese

In [131]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i600_l512.ckpt
Farring, haid,
and whine was now allows
and himsens the prosces, which
this say the carlong as him her had have
take her
wheles of
shimess, shaid of chele and and the sach of her hors, to diven to his souned hissely that the camt too and to as has her was his brough she sand as there would not to the mond that he weling all the hurd of her the must thay shis she had not said, and hord of her
was of her sainess, and wine the
marsing to hived to
the wert one
comeranite. "You was then the
souted in his all say...

"Whe colling the tore and were, was
serited to ham.

"I wand trook at antiththan to she to sher the ceratane. "I't to grink of the comt on the pain a pise to the mongrom.

"In what ha sid to the wase, but she sant her alexed some and thous shouse and thought hav into his sout, and was then
she tas say the fisticiant to all she had strook was
out, anowhen the conster of she had him seetend the minch, his bughere

In [132]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i1200_l512.ckpt
Farremed to the
sorn of his coming the
tabe, and same of the prancess that he was never to be seet
at the chulconess and and, at stalled as any
poored of the send of cares. And
the casion, said, and was not that that there had seemed
her husband, there had now
their the tristen, and thinker on the partered as the serventer, that him to the stile went and a sunder, shoulding the sore of horrial and husband that
was simply she wanted, who had some much she was till to seem he
had been both to be said the disprince all his sair, he can to him. How had been too much
any answorat were she
could said her. He had not a must
see he saw the clear, and the conscition if they. He went to be and taking and he wanced into she had been and talked in the pirters. And he had not happened, brugh taking only to the stood of the partion of this hand of
him at his head that she seat to give her too.

"Why dressed you thene way it all, I